#
#******************************************************************************
# @file        ci.yml
# @brief       File: ci.yml
# @author      Yoan Gilliand
# @editor      Yoan Gilliand
# @date        01 Dec 2025
#******************************************************************************
# @copyright   Copyright (c) 2025 Yoan Gilliand. All rights reserved.
#******************************************************************************
# @details
# GitHub Actions workflow for Continuous Integration.
#******************************************************************************
#
name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: SwiftLint
      run: |
        brew install swiftlint
        swiftlint lint --strict
    
    - name: Build
      run: |
        xcodebuild -project MacAppLocker.xcodeproj \
          -scheme MacAppLocker \
          -destination 'platform=macOS' \
          build
    
    - name: Run Tests
      run: |
        xcodebuild -project MacAppLocker.xcodeproj \
          -scheme MacAppLocker \
          -destination 'platform=macOS' \
          test
