#
#******************************************************************************
# @file        release.yml
# @brief       File: release.yml
# @author      Yoan Gilliand
# @editor      Yoan Gilliand
# @date        01 Dec 2025
#******************************************************************************
# @copyright   Copyright (c) 2025 Yoan Gilliand. All rights reserved.
#******************************************************************************
# @details
# GitHub Actions workflow for Release automation.
#******************************************************************************
#
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
    
    - name: Build Release
      run: |
        xcodebuild -project MacAppLocker.xcodeproj \
          -scheme MacAppLocker \
          -destination 'platform=macOS' \
          -configuration Release \
          clean build
          
    - name: Archive App
      run: |
        cd ~/Library/Developer/Xcode/DerivedData/MacAppLocker-*/Build/Products/Release
        zip -r MacAppLocker.zip MacAppLocker.app
        echo "ARCHIVE_PATH=$(pwd)/MacAppLocker.zip" >> $GITHUB_ENV
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.ARCHIVE_PATH }}
        generate_release_notes: true
